services:
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - "3000:3000"
    volumes:
      - /frontend
      - /node_modules
    stdin_open: true
    tty: true
    env_file:
      - ./frontend/themovies/.env.development
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./backend/data/:/backend/data
    environment:
       - DATABASE_URL=sqlite:///./data/themovies.db
       - PYTHONUNBUFFERED=1