services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /frontend
      - /node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - ./backend/data/:/backend/data
    environment:
       - DATABASE_URL=sqlite:///./data/themovies.db
       - PYTHONUNBUFFERED=1